# Generated by Django 4.2.4 on 2023-08-12 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=10000)),
                ('order', models.IntegerField()),
                ('type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('color', models.CharField(choices=[('menu', 'MENU'), ('date', 'DATE')], default='date', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Translate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2)),
                ('text', models.TextField(max_length=10000)),
                ('combine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prayer.phrase')),
            ],
        ),
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharase_count', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('singer', models.ManyToManyField(to='Prayer.singer')),
                ('tag', models.ManyToManyField(to='Prayer.tag')),
            ],
        ),
        migrations.AddField(
            model_name='phrase',
            name='Prayer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prayer.prayer'),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('relate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prayer.singer')),
            ],
        ),
    ]
